language: cpp

sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      env:
        - SCRIPT=build-pi.sh
        - MATRIX_EVAL="echo 'NOP'"

    - os: linux
      addons:
        apt:
          sources:
            # add PPAs with more up-to-date toolchains
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            # install toolchains
            - g++-5
      env:
        - SCRIPT=build.sh
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - g++-6
      env:
        - SCRIPT=build.sh
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - SCRIPT=build.sh
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.7
      env:
        - SCRIPT=build.sh
        - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7

    - os: osx
      osx_image: xcode8
      env:
        - SCRIPT=build-pi.sh
        - MATRIX_EVAL="echo 'NOP'"

    - os: osx
      osx_image: xcode8
      env:
        - SCRIPT=build.sh
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: osx
      osx_image: xcode8
      env:
        - SCRIPT=build.sh
        - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"

    - os: osx
      osx_image: xcode8
      env:
        - SCRIPT=build.sh
        - MATRIX_EVAL="brew install gcc && CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - sh ${SCRIPT}
