language: cpp

sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      env:
        - SCRIPT=build-pi.sh
        - MATRIX_EVAL="echo 'NOP'"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - SCRIPT=build.sh
        - MATRIX_EVAL="export CC=gcc-5 && export CXX=g++-5

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - SCRIPT=build.sh
        - MATRIX_EVAL="export CC=gcc-6 && export CXX=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - SCRIPT=build.sh
        - MATRIX_EVAL="export CC=clang-3.6 && export CXX=clang++-3.6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env:
        - SCRIPT=build.sh
        - MATRIX_EVAL="export CC=clang-3.7 && export CXX=clang++-3.7

    - os: osx
      osx_image: xcode8
      env:
        - SCRIPT=build-pi.sh
        - MATRIX_EVAL="echo 'NOP'"

    - os: osx
      osx_image: xcode8
      env:
        - SCRIPT=build.sh
        - MATRIX_EVAL="export CC=gcc-4.9 && export CXX=g++-4.9"

    - os: osx
      osx_image: xcode8
      env:
        - SCRIPT=build.sh
        - MATRIX_EVAL="brew install gcc5 && export CC=gcc-5 && export CXX=g++-5"

    - os: osx
      osx_image: xcode8
      env:
        - SCRIPT=build.sh
        - MATRIX_EVAL="brew install gcc && export CC=gcc-6 && export CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"
  - eval "${CC} --version"
  - eval "${CXX} --version"

script:
  - sh ${SCRIPT}
