language: cpp
sudo: required
dist: trusty
matrix:
  include:
  - os: linux
    env:
    - SCRIPT=build-pi.sh
  - os: linux
    env:
    - SCRIPT=build-pi-new.sh
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
    env:
    - SCRIPT=build.sh
    - COMP=gcc-5
    - COMPXX=g++-5
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - SCRIPT=build.sh
    - COMP=gcc-6
    - COMPXX=g++-6
script:
- if [[ "${COMP}" != "" ]]; then export CC=${COMP}; fi
- if [[ "${COMPXX}" != "" ]]; then export CXX=${COMPXX}; fi
- "${CXX} --version"
- sh ${SCRIPT}
notifications:
  slack:
    secure: Sp5s1J7h8ncDqumvILYMiBnydW9VPuoC4QaW/u3/3aEwYM2cYdBUphtnyIRkyB0pR1ja1TM42Bz+8hFyBcnFRWOzxx4caLV+xrQfoa6RjFAYZZWXOB7e5VnlOyrTMzhKt3cbI1P6kRSla1J1jbOpHhGaY18EBV+aF6VpLZ49XZQeo8BF4jGDcsyvrASeg77hz4uE+jY5IPmZVrqzRsAL8R+f/NuwtwpsEOsHis17aIHDGOYhg8VgNXD5Stgl6YMTXwyizTcTXn4o1OfwTQ6XSN0NpBNjQoyE52I/94GdWFqpm7+Z3PfYC5TxVwgTLrAh/wkqTaxV1Bu6MhYgc2udfEtHlBjaOecWXHjOj4md0p7wQFqxJkWjVL3qmam0y92PvnAmTuETpC+o7B+D8EL3Gg3o3HzaIQtWxIQx9ZhRA6Mv+YD+E6RXI3aRnqhfLLagNpzEEkM6DVv5e0hFipA/ayyOLdFBSM4H8QgmeLwxH/8L7rmyOB3dutb4+j5VzIRNA8bWk/INgZ7oVl6Tpx2Wo6Mi2KhcpKnpRQ1Rdg6JmOqx59yZbnzAiTotAa3uElKrEythFxYbKz5WMOjDumxWo4uD2Mq3voz7ZmcT0q18R4RMbgHN/i+uIKP8wvp+hx9+nFi2eOnh8vaNi0U8/fEsrhrPeKFkgYeEEGCBt0AqezA=
